name: MeteoSvizzera ICON-CH2 Evento 24h

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-meteoswiss-icon-ch2-evento:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev libnetcdff-dev libgl1

      - name: Install Conda and Metview
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: icon-env

      - name: Install Python Packages
        shell: bash -el {0}
        run: |
          conda install -c conda-forge metview metview-python requests pandas numpy

      - name: Esecuzione Script Pluviometrico Evento
        shell: bash -el {0}
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python CH2.py

      - name: Commit e Push Tracking Run
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ultima_ora_icon_ch2_evento.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Aggiornamento tracker RUN Evento ICON-CH2" && git push)
