name: ENS Rivoli

on:
  schedule:
    # Orari in UTC (CEST - 2 ore). 
    - cron: '*/30 * * * *'
  workflow_dispatch: 

jobs:
  crea_e_invia_grafici:
    runs-on: ubuntu-latest
    
    # Autorizzazione fondamentale per permettere al bot di salvare i file
    permissions:
      contents: write

    steps:
      - name: Estrazione del Codice Sorgente
        uses: actions/checkout@v3

      - name: Setup di Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installazione delle librerie
        run: pip install requests matplotlib

      - name: Generazione Grafici e Invio a Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python ens_rivoli.py --modello ch1
          python ens_rivoli.py --modello ch2
          python ens_rivoli.py --modello d2
          python ens_rivoli.py --modello arome
          python ens_rivoli.py --modello icon2i

      # QUESTO PASSAGGIO SALVA L'IMPRONTA DIGITALE PER LA VOLTA DOPO
      - name: Salva stato modelli per anti-spam
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Aggiornato stato hash modelli"
          file_pattern: "ultimo_hash_*.txt"
