name: Test API STAC Nativo (MeteoSwiss)

on:
  workflow_dispatch:

jobs:
  plot_map:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: System Dependencies (ecCodes)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-tools libeccodes-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Ecosistema MeteoSwiss (meteodata-lab)
        run: |
          git clone https://github.com/MeteoSwiss/opendata-nwp-demos.git
          cd opendata-nwp-demos
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-ansi

      - name: Esegui Python Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Copiamo lo script dentro la cartella clonata per accedere alle librerie installate
          cp test_ch2_stac.py opendata-nwp-demos/
          cd opendata-nwp-demos
          python icon_ch2_ens_map.py
