name: Generate ICON-CH2 Master Maps

on:
  schedule:
    - cron: '30 2,8,14,20 * * *'
  workflow_dispatch:

jobs:
  plot_master:
    runs-on: ubuntu-latest
    
    # Aumentato il timeout a 360 minuti (6 ore) massimo consentito
    timeout-minutes: 360 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: System Dependencies (ecCodes)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-tools libeccodes-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Ecosistema MeteoSwiss
        run: |
          git clone https://github.com/MeteoSwiss/opendata-nwp-demos.git
          cd opendata-nwp-demos
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-ansi

      - name: Esegui Master Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          cp icon_ch2_master.py opendata-nwp-demos/
          cd opendata-nwp-demos
          pip install pytz shapely
          python icon_ch2_master.py