name: Generate ICON-CH2 Hourly Albums

on:
  schedule:
    - cron: '15 2,8,14,20 * * *'
  workflow_dispatch:

jobs:
  plot_map:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: System Dependencies (ecCodes)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-tools libeccodes-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Ecosistema MeteoSwiss (meteodata-lab)
        run: |
          git clone https://github.com/MeteoSwiss/opendata-nwp-demos.git
          cd opendata-nwp-demos
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-ansi

      - name: Esegui Python Script Hourly
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          cp icon_ch2_hourly_albums.py opendata-nwp-demos/
          cp -r shapefiles opendata-nwp-demos/ || echo "Nessun shapefile trovato"
          cd opendata-nwp-demos
          pip install pytz shapely
          python icon_ch2_hourly_albums.py